version: 2.1
orbs:
  node: circleci/node@5.0.0

jobs:
  checkoutAndTest:
    executor: node/default
    steps:
      - node/test

workflows:
  test-and-deploy:
    jobs:
      - checkoutAndTest

      