version: 2.1
orbs:
  node: circleci/node@5.0.0

jobs:
  integrateFrontend:
    machine: true
    steps:
      - run: git clone https://github.com/marnade/3w5-h22-tp2-backend.git
      - run: git clone https://github.com/marnade/3w5-h22-tp2-frontend.git
      - run: cd 3w5-h22-tp2-frontend && npm i && npm run build
      - run: mkdir 3w5-h22-tp2-backend/public
      - run: cp 3w5-h22-tp2-frontend/build 3w5-h22-tp2-backend/public

workflows:
  test-and-deploy:
    jobs:
      - node/test #checkoutAndTest
      - integrateFrontend:
          requires: 
            - node/test

      